version: 2

# Specify the documentation subdirectory if applicable
# If your .readthedocs.yml is inside the 'documentation' folder, you can omit this
# Otherwise, include the 'subproject' field
# subproject: documentation

build:
  os: macos  # Choose 'linux', 'windows', or 'macos' based on your needs

python:
  version: 3.9  # Specify the Python version you are using
  install:
    - method: pip
      path: .  # Install the project in the root directory

sphinx:
  configuration: documentation/docs/conf.py  # Path to your Sphinx config file

# Optional: Specify additional dependencies or build steps
